#!/bin/bash
exec >>/var/log/vu-display-setup.log 2>&1
set -euo pipefail

export DISPLAY="${DISPLAY:-:0}"
export XAUTHORITY="${XAUTHORITY:-/var/run/lightdm/root/:0}"

read_rotation_file() {
    tr -d ' \t\r\n' </etc/vu/rotation 2>/dev/null || true
}

ROTATION_FILE="$(read_rotation_file)"
ROTATION="${1:-${ROTATION_FILE:-270}}"

case "$ROTATION" in
  0|normal)
    ANGLE=0
    XR="normal"
    M="1 0 0  0 1 0  0 0 1"
    ;;
  90|left)
    ANGLE=90
    XR="left"
    M="0 -1 1  1 0 0  0 0 1"
    ;;
  180|inverted)
    ANGLE=180
    XR="inverted"
    M="-1 0 1  0 -1 1  0 0 1"
    ;;
  270|right)
    ANGLE=270
    XR="right"
    M="0 1 0  -1 0 1  0 0 1"
    ;;
  *)
    echo "Unknown rotation '$ROTATION', fallback to 270/right"
    ANGLE=270
    XR="right"
    M="0 1 0  -1 0 1  0 0 1"
    ;;
esac

echo "=== $(date -Is) ROTATION=$ROTATION ANGLE=$ANGLE XR=$XR M=$M DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY ==="

mapfile -t CONNECTED_OUTPUTS < <(xrandr --query | grep " connected" | awk '{print $1}')
for OUTPUT in "${CONNECTED_OUTPUTS[@]}"; do
    if [[ "$OUTPUT" == DSI-* ]]; then
        TARGET_ROTATION="$XR"
        if ! xrandr --output "$OUTPUT" --rotate "$TARGET_ROTATION"; then
          echo "WARN: xrandr rotate failed for output '$OUTPUT' -> $TARGET_ROTATION"
        fi
    fi
done

mapfile -t POINTER_DEVICES < <(xinput list --short | grep -iE 'goodix|touch' | grep 'pointer' | grep -oP 'id=\K\d+')
for TOUCH in "${POINTER_DEVICES[@]:-}"; do
    props="$(xinput list-props "$TOUCH" 2>/dev/null || true)"
    if grep -q 'Coordinate Transformation Matrix' <<<"$props"; then
        if ! xinput set-prop "$TOUCH" 'Coordinate Transformation Matrix' $M; then
            echo "WARN: set CTM failed on id=$TOUCH"
        fi
    fi
done

# Persist state
install -d -m 0755 /etc/vu
printf '%d' "$ANGLE" > /etc/vu/rotation

# Persist Xorg libinput config (for device re-add / next boot)
install -d -m 0755 /etc/X11/xorg.conf.d
cat > /etc/X11/xorg.conf.d/90-libinput.conf <<EOF
# generated by vu-display-setup.sh at $(date -Is)
Section "InputClass"
    Identifier "libinput touchscreen catchall"
    MatchIsTouchscreen "on"
    MatchDevicePath "/dev/input/event*"
    Option "TransformationMatrix" "$M"
    Driver "libinput"
EndSection
EOF

echo "=== Done ==="

exit 0
