[Seat:*]
display-setup-script=/usr/share/lightdm/vu-display-setup.sh
greeter-wrapper=/etc/lightdm/vu-greeter-wrapper.sh
session-setup-script=/usr/share/lightdm/vu-session-setup.sh
session-cleanup-script=/usr/share/lightdm/vu-session-cleanup.sh
